enum EMatchEvent {
  MATCH_START = 1,
  FIRST_HALF_START = 2,
  FIRST_HALF_END = 3,
  SECOND_HALF_START = 4,
  SECOND_HALF_END = 5,
  MATCH_END = 6,

  GOAL = 7,
  OWN_GOAL = 8,
  PENALTY_GOAL = 9,
  FREE_KICK_GOAL = 10,

  PENALTY_AWARDED = 11,
  PENALTY_MISSED = 12,
  PENALTY_SAVED = 13,

  FREE_KICK_AWARDED = 14,
  CORNER_AWARDED = 15,

  YELLOW_CARD = 16,
  RED_CARD = 17,
  SECOND_YELLOW_RED_CARD = 18,

  SUBSTITUTION = 19,

  OFFSIDE = 20,
  FOUL = 21,
  HANDBALL = 22,

  INJURY = 23,

  VAR_CHECK = 24,
  VAR_GOAL_CONFIRMED = 25,
  VAR_GOAL_DISALLOWED = 26,

  KICK_OFF = 27,

  EXTRA_TIME_START = 28,
  EXTRA_TIME_END = 29,

  PENALTY_SHOOTOUT_START = 30,
  PENALTY_SHOOTOUT_END = 31,

  MATCH_ABANDONED = 32,
}

enum EMatchPlayerAction {
  TOUCH_BALL = 1,

  PASS = 2,
  SHORT_PASS = 3,
  LONG_PASS = 4,
  THROUGH_BALL = 5,
  CROSS = 6,
  ASSIST = 7,

  DRIBBLE = 8,
  SKILL_MOVE = 9,

  SHOOT = 10,
  LONG_SHOT = 11,
  FINESSE_SHOT = 12,
  VOLLEY_SHOT = 13,
  HEADER_SHOT = 14,

  GOAL = 15,
  OWN_GOAL = 16,

  PENALTY_SHOT = 17,
  FREE_KICK_SHOT = 18,

  TACKLE = 19,
  STANDING_TACKLE = 20,
  SLIDING_TACKLE = 21,

  INTERCEPTION = 22,
  BLOCK = 23,
  CLEARANCE = 24,

  DUEL_WON = 25,
  DUEL_LOST = 26,

  AERIAL_DUEL_WON = 27,
  AERIAL_DUEL_LOST = 28,

  RECOVER_BALL = 29,

  FOUL_COMMITTED = 30,
  FOUL_SUFFERED = 31,

  OFFSIDE = 32,

  YELLOW_CARD = 33,
  RED_CARD = 34,

  INJURED = 35,

  SAVE = 36,
  DIVING_SAVE = 37,
  REFLEX_SAVE = 38,
  PENALTY_SAVE = 39,
}

export { EMatchEvent, EMatchPlayerAction };
