enum EMatchEvent {
  MATCH_START = 1,
  FIRST_HALF_START = 2,
  FIRST_HALF_END = 3,
  SECOND_HALF_START = 4,
  SECOND_HALF_END = 5,
  MATCH_END = 6,

  GOAL = 7,
  FREE_KICK = 8,
  PASS = 35,
  SHOOT = 36,
  BLOCK = 37,
  GOALKEEPER_SAVE = 38,
  DRIBBLE = 39,
  INTERCEPTION = 40,
  SKILL_USED = 41,
  TACKLE = 42,
  SLIDE_TACKLE = 43,
  FIRST_HALF_STOPPAGE = 44,
  HALF_TIME_TUNNEL = 45,
  SECOND_HALF_STOPPAGE = 46,
  OFFSIDE = 47,
  GOAL_RESET = 48,
}

export { EMatchEvent };
