 enum EMatchEvent {
  MATCH_START = "MATCH_START",
  FIRST_HALF_START = "FIRST_HALF_START",
  FIRST_HALF_END = "FIRST_HALF_END",
  SECOND_HALF_START = "SECOND_HALF_START",
  SECOND_HALF_END = "SECOND_HALF_END",
  MATCH_END = "MATCH_END",

  GOAL = "GOAL",
  OWN_GOAL = "OWN_GOAL",
  PENALTY_GOAL = "PENALTY_GOAL",
  FREE_KICK_GOAL = "FREE_KICK_GOAL",

  PENALTY_AWARDED = "PENALTY_AWARDED",
  PENALTY_MISSED = "PENALTY_MISSED",
  PENALTY_SAVED = "PENALTY_SAVED",

  FREE_KICK_AWARDED = "FREE_KICK_AWARDED",
  CORNER_AWARDED = "CORNER_AWARDED",

  YELLOW_CARD = "YELLOW_CARD",
  RED_CARD = "RED_CARD",
  SECOND_YELLOW_RED_CARD = "SECOND_YELLOW_RED_CARD",

  SUBSTITUTION = "SUBSTITUTION",

  OFFSIDE = "OFFSIDE",
  FOUL = "FOUL",
  HANDBALL = "HANDBALL",

  INJURY = "INJURY",

  VAR_CHECK = "VAR_CHECK",
  VAR_GOAL_CONFIRMED = "VAR_GOAL_CONFIRMED",
  VAR_GOAL_DISALLOWED = "VAR_GOAL_DISALLOWED",

  KICK_OFF = "KICK_OFF",

  EXTRA_TIME_START = "EXTRA_TIME_START",
  EXTRA_TIME_END = "EXTRA_TIME_END",

  PENALTY_SHOOTOUT_START = "PENALTY_SHOOTOUT_START",
  PENALTY_SHOOTOUT_END = "PENALTY_SHOOTOUT_END",

  MATCH_ABANDONED = "MATCH_ABANDONED"
}

 enum EMatchPlayerAction {
  TOUCH_BALL = "TOUCH_BALL",

  PASS = "PASS",
  SHORT_PASS = "SHORT_PASS",
  LONG_PASS = "LONG_PASS",
  THROUGH_BALL = "THROUGH_BALL",
  CROSS = "CROSS",
  ASSIST = "ASSIST",

  DRIBBLE = "DRIBBLE",
  SKILL_MOVE = "SKILL_MOVE",

  SHOOT = "SHOOT",
  LONG_SHOT = "LONG_SHOT",
  FINESSE_SHOT = "FINESSE_SHOT",
  VOLLEY_SHOT = "VOLLEY_SHOT",
  HEADER_SHOT = "HEADER_SHOT",

  GOAL = "GOAL",
  OWN_GOAL = "OWN_GOAL",

  PENALTY_SHOT = "PENALTY_SHOT",
  FREE_KICK_SHOT = "FREE_KICK_SHOT",

  TACKLE = "TACKLE",
  STANDING_TACKLE = "STANDING_TACKLE",
  SLIDING_TACKLE = "SLIDING_TACKLE",

  INTERCEPTION = "INTERCEPTION",
  BLOCK = "BLOCK",
  CLEARANCE = "CLEARANCE",

  DUEL_WON = "DUEL_WON",
  DUEL_LOST = "DUEL_LOST",

  AERIAL_DUEL_WON = "AERIAL_DUEL_WON",
  AERIAL_DUEL_LOST = "AERIAL_DUEL_LOST",

  RECOVER_BALL = "RECOVER_BALL",

  FOUL_COMMITTED = "FOUL_COMMITTED",
  FOUL_SUFFERED = "FOUL_SUFFERED",

  OFFSIDE = "OFFSIDE",

  YELLOW_CARD = "YELLOW_CARD",
  RED_CARD = "RED_CARD",

  INJURED = "INJURED",

  SAVE = "SAVE",
  DIVING_SAVE = "DIVING_SAVE",
  REFLEX_SAVE = "REFLEX_SAVE",
  PENALTY_SAVE = "PENALTY_SAVE",

  CLAIM_CROSS = "CLAIM_CROSS",
  PUNCH_BALL = "PUNCH_BALL",

  THROW_BALL = "THROW_BALL",

  SUBBED_IN = "SUBBED_IN",
  SUBBED_OUT = "SUBBED_OUT"
}

export { EMatchEvent, EMatchPlayerAction };